FROM mysql

ENV MYSQL_ROOT_PASSWORD="mysecretpassword"
ENV MYSQL_DATABASE="mysql"
ENV MYSQL_USER="mysqlUser"
ENV MYSQL_PASSWORD=="mysecretpassword"
VOLUME [ "/my/own/datadir:/var/lib/mysql" ]    

EXPOSE 3306