version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:5000
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
    restart: on-failure

volumes:
  jenkins: