plugin: aws_ec2
regions:
  - eu-central-1
keyed_groups:
  #  each aws ec2 instance has it own instance tags. create  
  #  a tag variable from those tags for ansible to use. 
  #  if an EC2 tag:Name is acloudguru_machine, it'll be converted to the
  #  Ansible tag variable name as follows: tag_Name_acloudguru_machine
  # which can then be passed as a variable value for the host via -e flag
  - key: tags
    prefix: tag

hostnames:
  - ip-address
  - dns-name
  - 'tag:Name'
compose:
  ansible_host: public_dns_name
  ansible_user: "'ubuntu'"