---
- hosts: all
  become: true
  vars:
    container_name: "{{ lookup('ansible.builtin.env', 'CONTAINER_NAME') }}"     
    container_image: "{{ lookup('ansible.builtin.env', 'CONTAINER_IMAGE') }}"   

  tasks:
    - name: Login to Dockerhub
      community.docker.docker_login:
        username: "{{ lookup('ansible.builtin.env', 'DOCKERHUB_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'DOCKERHUB_TOKEN') }}"

    - name: Pull app Docker image
      community.docker.docker_image:
        name: "{{ container_image }}"
        source: pull

    - name: Delete old app container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name:  Create and start app container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        published_ports: 8081:8081
        state: started
        