name: deploy infrastructure 
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
env:
  path: docker-gs-ping
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.4
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch required Go modules
        run:  go mod init
      - name: Build
        run:  go build -v ./docker-gs-ping/...
  
      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with: 
          path: /tmp/.buildx-cache
          key:  ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push:    false
          load:    true
          tags: ${{ github.event.repository.name }}:latest, ${{ github.repository }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to:   type=local,dest=/tmp/.buildx-cache

      - name: Run functional tests
        run:  go test -v ./docker-gs-ping/...
